sources:
  - name: staging
    database: DFA23RAWDATA
    schema: RAWDATA

    
    tables:
      - name: CROPDATARAW
      - name: IRRIGATIONDATARAW
      - name: LOCATIONDATARAW
      - name: PESTDATARAW
      - name: SENSORDATARAW
      - name: SOILDATARAW
      - name: WEATHERDATARAW